export const AppRoutes = {
  home: "/",
  forums: "/forums",
  forumsNew: "/forums/new",
  forumDetail: (id: string) => `/forums/${id}`,
  jobs: "/jobs",
  jobDetail: (id: string) => `/jobs/${id}`,
  courses: "/courses",
  courseDetail: (id: string) => `/courses/${id}`,
  about: "/about",
  profile: "/profile",
  profileEdit: "/profile/edit",
  guidelines: "/guidelines",
  report: "/report",
  terms: "/terms",
  privacy: "/privacy",
  disclaimer: "/disclaimer",
  dmca: "/dmca",
  auth: "/auth",
  authForgotPassword: "/auth/forgot-password",
  login: "/auth",
  register: "/auth?tab=register",
  search: "/search",
  publicProfile: (username: string) => `/u/${username}`,
} as const;

export type AppRoute = (typeof AppRoutes)[keyof typeof AppRoutes];
