// Mock data for when API is unavailable
import type { Course, Job, Notification, Reply, Thread } from "@/types";
export const mockThreads: Thread[] = [
  {
    id: '1',
    title: 'Best practices for React hooks in 2025',
    body: 'I was wondering what are the best practices for using React hooks in modern applications. Any suggestions?',
    author: { id: 'u1', username: 'chioma_dev', displayName: 'Chioma Dev', avatarUrl: '👩‍💻' },
    categoryId: 'technology',
    tags: ['react', 'hooks'],
    likeCount: 24,
    viewCount: 156,
    replyCount: 8,
    createdAt: new Date('2025-12-20').toISOString(),
  },
  {
    id: '2',
    title: 'How to optimize Next.js performance',
    body: 'Share your tips and tricks for making Next.js apps lightning fast',
    author: { id: 'u2', username: 'tunde_code', displayName: 'Tunde Code', avatarUrl: '👨‍💻' },
    categoryId: 'technology',
    tags: ['nextjs', 'performance'],
    likeCount: 45,
    viewCount: 312,
    replyCount: 12,
    createdAt: new Date('2025-12-18').toISOString(),
  },
  {
    id: '3',
    title: 'TypeScript vs JavaScript - pros and cons',
    body: 'Starting a new project and trying to decide between TS and JS. What are your experiences?',
    author: { id: 'u3', username: 'ada_coder', displayName: 'Ada Coder', avatarUrl: '👩‍🔬' },
    categoryId: 'technology',
    tags: ['typescript'],
    likeCount: 67,
    viewCount: 489,
    replyCount: 23,
    createdAt: new Date('2025-12-15').toISOString(),
  },
]

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Product Designer',
    company: 'Paystack',
    location: 'Lagos (Hybrid)',
    type: 'full-time',
    salary: '₦1.2M - 1.8M',
    description: 'Lead product design for payment experiences across Africa.',
    verified: true,
    postedAt: '2 days ago',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKqG4cnG4EwJMC5gG9_BTIl4d42EnKGktXEs6RuJOkECW72arYeh81Baf4Kq_hRy7JOV7fH2-6FAsWFPSDmq_-wXAmvDYMaMiHR6U5ZlN_fKRcV0ZjAABOrc1eEA7mcEYsBdNGcfREAHGqGR9Y2Q4JMnfFHrDXWizeRW0lTDKefMbW7du7gFiRGbU8Y_WZbi4rc8dLZHpghIcB8Co-n-bM8vDQCLmLyFzDLW-O-KFU-QEpQbWGC37Sgpbr8UMmhuMOSxmsXKH8hnQ',
    logoBg: 'primary-fixed',
    matchPercent: 95,
    tags: ['Full-time', '95% Match', '₦1.2M - 1.8M'],
    category: 'design',
    remote: false,
  },
  {
    id: '2',
    title: 'UX Researcher',
    company: 'Flutterwave',
    location: 'Remote',
    type: 'contract',
    salary: 'Negotiable',
    description: 'Run user research sprints for fintech products.',
    verified: true,
    postedAt: '5 hours ago',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzIo1eP2Cqcsau3V8X6LN7Il_trL84Nk8nlCgfAfr8G_sjQLiaxy2QQEp0vWazCegXsnjRAkKYX0gY1wJXQX3QEqzTsZG1m18KKzL6vNkjvqWN2EbtfiDV8IRlYVFYJvhuuC8vZKZyErqMmSKdPrnFfwZZGEN6V2YVnQ2nVmGpJBj1mzL1zaKafxDQN8GMXZnlBJdIAsAd4uctlhsemYMBQkmqCsI40Wo4x0VJOK9cDVcXeGFtG4q6xDVhBlJFdDm2i4p35qmdFY4',
    logoBg: 'surface-container',
    matchPercent: 88,
    tags: ['Contract', '88% Match', 'Negotiable'],
    category: 'design',
    remote: true,
  },
  {
    id: '3',
    title: 'Interface Designer',
    company: 'Kuda Bank',
    location: 'Lagos (On-site)',
    type: 'full-time',
    salary: '₦800k+',
    description: 'Design mobile banking interfaces for millions of users.',
    verified: false,
    postedAt: '1 week ago',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClEm4_Qf4HvLEVv0SbUQeLNtygd-HedcL6vGW76m0i4k1ILJw6zQ99is7NIhNN1QhYq3xFbD78Xp6JD8d3-RRwIv3xW2w5cG9fPjEFKjbLWqndSr5QRKEtW7HD8VuPpvA9H1czCyFxD2vFIoAVDjLf7MdJSghnCVhsq7_6aoxKUneewVPtQK6eN5ASaJn1neniF48NfVEM_AoW5qrhoAIdRr2BxTMH6qC9VmbrZemU2gwQELhdkmKawh9sytmpnLaJ3-1_q4H60cE',
    logoBg: 'primary-fixed',
    tags: ['Full-time', 'Direct Hire', '₦800k+'],
    category: 'design',
    remote: false,
  },
  {
    id: '4',
    title: 'Interaction Designer',
    company: 'Moniepoint',
    location: 'Remote',
    type: 'freelance',
    salary: 'USD 2k - 4k',
    description: 'Short-term engagement for merchant dashboard redesign.',
    verified: true,
    postedAt: 'Just now',
    logoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDTnOmoWhVK71kD854TPS2NXC-aA2cFOtbf9a2mQQLRaRxTuK_NPwNFZFgzCtv24sQAcIYe6vNi3a9doDDBFXsCuCBqkyd6xw5LWUeDSelt_8yuUC_VPnFnXNi7LNyTYr4h1iO8TpYpi1A-6lp9N9g8Id_KSuNwbUlYyo5dKa91CNTl-6D5ah48IOGM7yHMksSTorrdPfKq91n0seVNMFq0IwXs31A5pScSHY3RgWuOuE6_geJan1o98Nerw5E1FeX34bHhV6K82JE',
    logoBg: 'surface-container',
    tags: ['Freelance', 'Urgent', 'USD 2k - 4k'],
    category: 'design',
    remote: true,
  },
  {
    id: '5',
    title: 'Senior React Developer',
    company: 'Flutterwave',
    location: 'Lagos, Nigeria',
    type: 'full-time',
    salary: '₦2.5M - 3.5M /month',
    description: 'Looking for experienced React developers to join our growing team',
    verified: true,
    postedAt: '3 days ago',
    tags: ['React', 'TypeScript', 'Node.js'],
    category: 'development',
    remote: false,
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'Andela',
    location: 'Remote',
    type: 'full-time',
    salary: '₦2M - 3M /month',
    description: 'Manage and optimize our cloud infrastructure',
    verified: true,
    postedAt: '4 days ago',
    tags: ['AWS', 'Docker', 'Kubernetes'],
    category: 'development',
    remote: true,
  },
]

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'UI/UX Design Level Up with Prototyping',
    provider: 'i9 Academy',
    level: 'intermediate',
    category: 'UI/UX Design',
    rating: 4.9,
    free: true,
    studentCount: 1200,
    duration: '12h 45m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzikraBm3oOBuXVEDz-qKDVcDzLVXqQjlbHgzxHoBtUXTWxgbMJDM5UdQH94KtoDAriyosMqVoLmB_CpmYz4nryEHfRwQgEVuPA8pOn9KQq5lbqUNR6y_7eCq1zhvkpMy6iHbcQ87Pj3A9xJiLgRb3Ov1b7_l1gQgscGh1LOuM2npgJfQI-ARgOgVkd1my8gKAuUx2UY50hoepANlGqQOpjlKb0OhMIew1ulGxnVwVsqgO4PEHaLoAqYPR84uQM0w2UQVIygE9jBE',
    imageBg: 'primary-fixed',
    providerInitials: 'i9',
    providerAvatarBg: 'primary-fixed',
  },
  {
    id: '2',
    title: 'Graphic Design Masterclass: Adobe Illustrator',
    provider: 'Design Tribe',
    level: 'intermediate',
    category: 'Graphic Design',
    rating: 4.7,
    free: true,
    studentCount: 850,
    duration: '8h 20m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpIU8TJR2OvOes-gbtRDfJ4m3Rv_5UgZ1XL8JDAsuzh6FQ-YOr77THBePJG1mGlITmTtAlFvpTef7CE0Lz7zVv_mMWeepurriKPf7ldaX_9Dr4M4DO51dlzJqdrxFEJWTKor2hGFJkNQM4LuEICIIkGnP6dTLBDvoupNyJwDxQVk3e86ie7Ucl2xHgWkMP0PWpnk3N3E20S-APmHkl0u6AsoLK9fMcZYpRXFGyDnkpqqjfWmeTvNCNjlE_Wx53jo03EPruu8DTefA',
    imageBg: 'tertiary-fixed',
    providerInitials: 'DT',
    providerAvatarBg: 'secondary-fixed',
  },
  {
    id: '3',
    title: 'Low Code Website Development Guide',
    provider: 'Lagos Codes',
    level: 'beginner',
    category: 'Web Development',
    rating: 4.8,
    free: true,
    studentCount: 2400,
    duration: '15h 10m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeiDZsJCENAgU_0IhrwbXSveMH1A4zQ_7e2_luZr_cKJV7A-Xk-rvK7aQqmKmKGa3Uh5t9sg3dYdVVIIBmvjbneI7N_JrqOEPH73qyQ01nvzBybvVbYRnLZ6FKNY3O8AyzOtBziiSR1ERgxSzGwOoyOu4l2BkrnjNXP9cJ60l_jhWb9lkjp7XcP7J6ZtrrGYNv79cGUUc0z8hkLYHreg7kLqmYTY4DVqu2ePY0ScWtcbhcuz1g6KZkxYiW1rn3IudCOvZFqF25OzA',
    imageBg: 'secondary-fixed-dim',
    providerInitials: 'LC',
    providerAvatarBg: 'primary-container',
  },
  {
    id: '4',
    title: 'Brand Identity & Visual Expression',
    provider: 'Brand Masters',
    level: 'advanced',
    category: 'Branding',
    rating: 4.6,
    free: true,
    studentCount: 420,
    duration: '6h 30m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXBRYSa_5FVsNpgeD1rg5gX4HGO1r9nMK5zVAi3gb4wOrIA5_ZhtHvUi-RdnTjjmhTATSTTuMQc0FrRLlxcnBoEOsSOQAXoRsvZfoIs8ThUnO9tDgxlxQFMcblHZP1Nkjs1Jt-gtF6EF7ilW0_9s9idePRN1tL3ivAwyA_PU2j6wq2M3fdGpUQeh-0-YdjAU3BRuRrW7htKdbuJl4azewVD1Doj6_v8tdg0aBylUEcVK7-8hxuGmChCDt_GhUE56CSRQiPU-nhT_A',
    imageBg: 'primary-fixed-dim',
    providerInitials: 'BM',
    providerAvatarBg: 'outline-variant',
  },
  {
    id: '5',
    title: 'Figma UI/UX Design Essential',
    provider: 'i9 Academy',
    level: 'beginner',
    category: 'UI/UX Design',
    rating: 4.9,
    free: true,
    studentCount: 3100,
    duration: '20h 00m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMXKc4mjI5250LK_tieXnbAuKFaeErU7lzf9o-D9aUsr9skiiqoip4RqrNd75u17S94B8xKhZkKC0QL65UqiQe-J2tbhnizmlVUq471EuuRS5E3g-ARe-rLI4Lroa18l98JaqTV4dg7sVAIMR_ICBQHIJnnKb_TjhyK0KUlSpWuUyUwuSm47m_Zl5m6lDA7w2bS0wShA3beY-6TnchtEJttK9RsdU0mQxEaUxY7ALhJ0j91HLGamWrU8WIArntogQnxAvfzp3SevI',
    imageBg: 'error-container',
    providerInitials: 'i9',
    providerAvatarBg: 'primary-fixed',
  },
  {
    id: '6',
    title: 'Fundamental 2D Animation Using Jitter',
    provider: 'Jitter Academy',
    level: 'beginner',
    category: 'Animation',
    rating: 4.5,
    free: true,
    studentCount: 600,
    duration: '5h 45m',
    verified: true,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAnn9w1hP82NKHlHe-cBXBXTrVF6uUWg3XXW5nSkX12uMvldwx0f6-odFYKRpOdqf7DB2uR4v-1RFTn6eTXt35Mb1_uU0iLRP_EqZUupQGyH__SdnzszT2gB67mUdb_2OsBJXJPlMqEFN4uPYLYx0AlCjsuDEfEHFc3J-lk201_aUVFknKgrpOczkz2PI_3KFnovV0zu-RV5oUsusS6n4ZSP9t7vnDzULIAmgfTu5Ph5VWQU90l6BstiJEIjmuTFLjyhWUNObeIZeY',
    imageBg: 'surface-container-highest',
    providerInitials: 'JA',
    providerAvatarBg: 'tertiary-fixed',
  },
]

export const mockReplies: Record<string, Reply[]> = {
  '1': [
    {
      id: 'r1',
      body: 'Great question! I always use custom hooks for reusable logic',
      author: { id: 'u4', username: 'zainab_tech', displayName: 'Zainab Tech', avatarUrl: '👩‍💼' },
      createdAt: new Date('2025-12-19').toISOString(),
    },
    {
      id: 'r2',
      body: 'Make sure to memoize your callbacks with useCallback to avoid performance issues',
      author: { id: 'u5', username: 'emeka_pro', displayName: 'Emeka Pro', avatarUrl: '👨‍🎓' },
      createdAt: new Date('2025-12-19').toISOString(),
    },
  ]
}

export const mockSearchResults = {
  threads: mockThreads.slice(0, 2),
  jobs: mockJobs.slice(0, 2),
  courses: mockCourses.slice(0, 2),
  users: [
    { id: 'u1', displayName: 'Chioma Dev', username: 'chioma_dev', avatarUrl: '👩‍💻', verified: true },
    { id: 'u2', displayName: 'Tunde Code', username: 'tunde_code', avatarUrl: '👨‍💻', verified: false },
  ],
}

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'reply' as const,
    message: 'Tunde Code replied to your thread about React hooks',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    href: '/forums/1',
  },
  {
    id: 'n2',
    type: 'job_match' as const,
    message: 'New job match: Senior React Developer at Flutterwave',
    read: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    href: '/jobs/5',
  },
  {
    id: 'n3',
    type: 'new_course' as const,
    message: 'New free course: Figma UI/UX Design Essential',
    read: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    href: '/courses/5',
  },
  {
    id: 'n4',
    type: 'mention' as const,
    message: 'Ada Coder mentioned you in a discussion',
    read: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    href: '/forums/3',
  },
]
